import { ArrowLeft, LockKeyhole } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useStore } from '../../app/useStore';
import { getProductById, getVariant } from '../../features/catalog/api';
import { formatMoney } from '../../lib/money';

export default function PaymentPage() {
  const { lines, subtotalPaise } = useStore();
  return <div className="checkout-page container"><Link className="back-link" to="/shop"><ArrowLeft size={17} /> Continue shopping</Link><div className="checkout-intro"><span className="eyebrow">YOUR BAG</span><h1>Checkout <em>preview.</em></h1><p>Review your selection. Payment and order placement will be available after secure checkout is connected.</p></div>{!lines.length ? <div className="checkout-empty"><h2>Your bag is empty.</h2><p>Find a piece to make yours.</p><Link className="button button-dark" to="/shop">Explore the collection</Link></div> : <div className="checkout-grid"><section className="checkout-panel"><h2>Contact &amp; delivery</h2><p>Address and delivery options will be available when checkout services are connected.</p><div className="disabled-field">Contact information <span>Coming soon</span></div><div className="disabled-field">Delivery address <span>Coming soon</span></div><h2>Payment</h2><div className="payment-notice"><LockKeyhole size={21} /><span>Payment is unavailable in this preview. No card details are collected.</span></div><button className="button button-dark full" type="button" disabled>Payment coming soon</button></section><aside className="checkout-panel checkout-summary"><h2>Order summary</h2>{lines.map((line) => { const product = getProductById(line.productId); const variant = getVariant(line.productId, line.variantId); if (!product || !variant) return null; return <div className="checkout-line" key={line.variantId}><img src={product.images[0]?.url || '/product-placeholder.svg'} alt={product.images[0]?.alt || product.name} /><div><strong>{product.name}</strong><span>{[variant.color, variant.size].filter(Boolean).join(' · ')} · Qty {line.quantity}</span><b>{formatMoney({ amountPaise: variant.price.amountPaise * line.quantity })}</b></div></div>; })}<div className="checkout-total"><span>Subtotal</span><strong>{formatMoney({ amountPaise: subtotalPaise })}</strong></div><p>Delivery, tax, and final totals will be confirmed by the store service before payment.</p></aside></div>}</div>;
}
